# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_app', '0002_show_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
